[build]
builder = "nixpacks"

# Service 1: Santi ERP Service (Bridge/Backend)
[[services]]
name = "proxy"
root = "apps/proxy"
watchPaths = ["apps/proxy/**"]
buildCommand = "npm install && npm run build"
startCommand = "npm run start"


